---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Baixar ou atualizar material

```
install.packages("remotes")
remotes::install_github("curso-r/CursoR")

CursoR::atualizar_material()
```

```{r, echo = FALSE}
knitr::kable(escape = FALSE,
  tibble::tibble(
    slide = CursoR:::list_github_files("intro-ml-mestre", "slides/", "\\.html"),
    link = paste0("https://curso-r.github.io/intro-ml-mestre/", slide)
  ) %>%
    mutate(
      Slides = glue::glue("<a href='{link}'>{slide}</a>")
    ) %>% 
    select(Slides)
)
```

```{r, echo = FALSE}
knitr::kable(
  tibble::tibble(
    exemplo =  CursoR:::list_github_files("intro-ml-mestre", "exemplos/", "\\.R"),
    link = paste0("https://curso-r.github.io/intro-ml-mestre/exemplos/", exemplo)
  ) %>%
    mutate(
      Exemplos = glue::glue("<a href='{link}'>{exemplo}</a>")
    ) %>% 
    select(Exemplos)
)
```

```{r, echo = FALSE}
knitr::kable(
  tibble::tibble(
    scripts_feitos_em_aula =  CursoR:::list_github_files("202006-intro-ml", "scripts_feitos_em_aula/", "\\.R"),
    link = paste0("https://curso-r.github.io/202006-intro-ml/scripts_feitos_em_aula/", scripts_feitos_em_aula)
  ) %>%
    mutate(
      `Scripts feitos em aula` = glue::glue("<a href='{link}'>{scripts_feitos_em_aula}</a>")
    ) %>% 
    select(`Scripts feitos em aula`)
)
```

```{r, echo = FALSE}
knitr::kable(
  tibble::tibble(
    exercicio = CursoR:::list_github_files("intro-ml-mestre", "exercicios/", "\\.R"),
    link = paste0("https://curso-r.github.io/intro-ml-mestre/exercicios/", exercicio)
  ) %>%
    mutate(
      Exercícios = glue::glue("<a href='{link}'>{exercicio}</a>")
    ) %>% 
    select(Exercícios)
)
```


